# Application Configuration
spring:
  application:
    name: SERVICE-REGISTRY

# Server Configuration
server:
  port: 8761

# Eureka Server Configuration
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
